using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NeverOrder.Domain.Carts;
using NeverOrder.Domain.Orders;
using NeverOrder.Infrastructure.Persistence;

namespace NeverOrder.Tests.Integration.Persistence;

/// <summary>
/// Every aggregate assigns its own Guid id. Guid keys are store-generated by convention, which makes
/// EF treat a child reached through a tracked parent's navigation as an existing row and emit an
/// UPDATE that matches nothing. These tests pin the mapping that keeps them inserts.
/// No database is contacted: building the model and running change detection are both in-process.
/// </summary>
public sealed class DomainAssignedKeyTests : IDisposable
{
    private readonly NeverOrderDbContext _db;

    public DomainAssignedKeyTests()
    {
        var options = new DbContextOptionsBuilder<NeverOrderDbContext>()
            .UseNpgsql("Host=localhost;Database=never-connected")
            .Options;

        _db = new NeverOrderDbContext(options);
    }

    public void Dispose() => _db.Dispose();

    [Theory]
    [InlineData(typeof(Cart))]
    [InlineData(typeof(CartItem))]
    [InlineData(typeof(Order))]
    [InlineData(typeof(OrderItem))]
    [InlineData(typeof(OrderStatusHistory))]
    public void Guid_keys_are_never_store_generated(Type entityType)
    {
        var key = _db.Model.FindEntityType(entityType)!.FindPrimaryKey()!;

        key.Properties.Should().ContainSingle()
            .Which.ValueGenerated.Should().Be(ValueGenerated.Never);
    }

    [Fact]
    public void Adding_an_item_to_a_tracked_cart_is_an_insert()
    {
        var cart = new Cart(Guid.NewGuid(), DateTimeOffset.UtcNow);
        _db.Attach(cart);

        cart.AddOrIncrease(Guid.NewGuid(), "Masala Chai Sampler", 999m, 2, DateTimeOffset.UtcNow);
        _db.ChangeTracker.DetectChanges();

        _db.Entry(cart.Items.Single()).State.Should().Be(EntityState.Added);
    }

    [Fact]
    public void Advancing_a_tracked_order_inserts_its_new_status_row()
    {
        var now = DateTimeOffset.UtcNow;
        var order = Order.Create(
            Guid.NewGuid(),
            "NO-000001",
            new[] { new OrderItem(Guid.NewGuid(), "Masala Chai Sampler", 999m, 1) },
            deliveryFee: 0m,
            now);

        // Attach models the real flow: the order is loaded from the database, then advanced.
        _db.Attach(order);

        order.TransitionTo(OrderStatus.Confirmed, now, "Confirmed by the consumer.");
        _db.ChangeTracker.DetectChanges();

        var added = order.StatusHistory.Single(h => h.ToStatus == OrderStatus.Confirmed);
        _db.Entry(added).State.Should().Be(EntityState.Added);
    }
}
