using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NeverOrder.Application.Abstractions;
using NeverOrder.Domain.Carts;
using NeverOrder.Domain.Catalog;
using NeverOrder.Domain.Events;
using NeverOrder.Domain.Orders;
using NeverOrder.Infrastructure.Identity;

namespace NeverOrder.Infrastructure.Persistence;

public sealed class NeverOrderDbContext
    : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>, IApplicationDbContext
{
    public NeverOrderDbContext(DbContextOptions<NeverOrderDbContext> options) : base(options)
    {
    }

    public DbSet<Product> Products => Set<Product>();

    public DbSet<Category> Categories => Set<Category>();

    public DbSet<Cart> Carts => Set<Cart>();

    public DbSet<Order> Orders => Set<Order>();

    public DbSet<OutboxMessage> OutboxMessages => Set<OutboxMessage>();

    public DbSet<ProcessedEvent> ProcessedEvents => Set<ProcessedEvent>();

    public DbSet<DeadLetterEvent> DeadLetterEvents => Set<DeadLetterEvent>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.ApplyConfigurationsFromAssembly(typeof(NeverOrderDbContext).Assembly);

        UseDomainAssignedKeys(builder);
    }

    /// <summary>
    /// Domain constructors assign their own <see cref="Guid"/> ids. Guid keys are store-generated by
    /// convention, and for a child reached through a tracked parent's navigation EF reads
    /// "key already set + store-generated" as an existing row: it emits an UPDATE that matches nothing
    /// instead of an INSERT. Declaring the keys never-generated makes EF mark them Added.
    /// </summary>
    private static void UseDomainAssignedKeys(ModelBuilder builder)
    {
        var domainAssembly = typeof(Order).Assembly;

        foreach (var entityType in builder.Model.GetEntityTypes())
        {
            if (entityType.ClrType.Assembly != domainAssembly)
            {
                continue;
            }

            var primaryKey = entityType.FindPrimaryKey();
            if (primaryKey is null)
            {
                continue;
            }

            foreach (var property in primaryKey.Properties.Where(p => p.ClrType == typeof(Guid)))
            {
                property.ValueGenerated = ValueGenerated.Never;
            }
        }
    }
}
